name: relationship_navigator
description: A personal relationship-insight and decision-support app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Backend & Data
  supabase_flutter: ^2.0.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.2
  
  # Utilities
  uuid: ^4.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # UI Components
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  syncfusion_flutter_charts: ^23.1.44
  fl_chart: ^0.64.0
  
  # Permissions & Platform
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  
  # Messages & SMS (Android)
  sms_maintained: ^0.2.3
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  
  # Encryption & Security
  encrypt: ^5.0.1
  crypto: ^3.0.3
  
  # AI & NLP
  tflite_flutter: ^0.10.4
  
  # Date & Time
  table_calendar: ^3.0.9
  
  # File handling
  file_picker: ^6.1.1
  
  # Animations
  lottie: ^2.7.0
  
  # Theme & Styling
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting & Analysis
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/data/
    - assets/models/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
